-- Resturant Databse

-- Start Table Creations --

-- Start Abdelrhman Section --

--
-- Table structure for table `CHEF`
--

CREATE TABLE IF NOT EXISTS CHEF (
    EMP_ID		     INT PRIMARY KEY NOT NULL,
    CHEF_NAME        CHAR(10) DEFAULT NULL,
    SALARY           FLOAT(7,2) DEFAULT NULL,
    DATAOFBRINTH     DATE DEFAULT NULL,
    BID_FK	         INT NOT NULL REFERENCES BRANCES(BID)
 );



--
-- Table structure for table `WAITERS`
--

CREATE TABLE IF NOT EXISTS WAITERS (
    EMP_ID		     INT PRIMARY KEY NOT NULL,
    WAITER_NAME      CHAR(10) DEFAULT NULL,
    SALARY           FLOAT(7,2) DEFAULT NULL,
    DATAOFBRINTH     DATE DEFAULT SYSDATE(),
    BID	             INT NOT NULL REFERENCES BRANCHES(BID)
 );




--
-- Table structure for table `DELIVERYBOY`
--

CREATE TABLE IF NOT EXISTS DELIVERYBOY (
    EMP_ID		     INT PRIMARY KEY NOT NULL,
    D_NAME           CHAR(10) DEFAULT NULL,
    SALARY           FLOAT(7,2) DEFAULT NULL,
    DATA_OF_BRITH    DATE DEFAULT SYSDATE(),
    BID	             INT NOT NULL REFERENCES BRANCES (BID)
);

-- End Abdelrhman Section --


-- Start Adham Section --

-- Branches Table
CREATE TABLE IF NOT EXISTS BRANCHES (
    BID INT PRIMARY KEY NOT NULL,
    BRANCH_NAME VARCHAR(10) DEFAULT NULL,
    BRANCH_ADDRESS VARCHAR(10) DEFAULT NULL
);

-- Orders Table
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT PRIMARY KEY NOT NULL,
    ORDER_TIME TIME,
    ORDER_DATE DATE,
    TICKET_NO INT,
    BID INT NOT NULL REFERENCES BRANCES (BID),
    CID INT NOT NULL REFERENCES CUSTOMERS (CID),
    PAYMENT_ID INT NOT NULL REFERENCES PAYMENT (PAYMENT_ID)
);

-- Customers Table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CID INT PRIMARY KEY NOT NULL,
    PHONE VARCHAR(20) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(20) NOT NULL,
    CUSTOMER_ADR VARCHAR(20)
);

-- End Adham Section --

-- Start Marawan Section --

-- Payment Table

CREATE TABLE IF NOT EXISTS PAYMENT (
    PAYMENT_ID INT PRIMARY KEY NOT NULL,
    NET_PRICE INT,
    CHASH_PAID INT,
    DOB DATE DEFAULT SYSDATE() 
);

-- Food Item
CREATE TABLE IF NOT EXISTS FOOD_ITEMT (
    FID INT PRIMARY KEY NOT NULL,
    FOOD_NAME VARCHAR(20),
    PRICE FLOAT(4,1),
    ORDER_ID INT NOT NULL REFERENCES ORDERS(ORDER_ID)
);
-- End Marawan Section --

-- End Table Creations --


-- Insert Statements --